version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8181:80"
    container_name: frontend_container 
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend_container 